"""Curated list + parsed dump -> data/cars.js + data/cars.json (game data)."""
import json, re, os, sys
sys.path.insert(0, os.path.dirname(__file__))
from curated import CARS
HERE = os.path.dirname(__file__)
d = json.load(open(os.path.join(HERE, '..', 'data-src', 'parsed.json'), encoding='utf-8'))
F = ['hp', 'torque', 'accel', 'topSpeed', 'weight']
ALIAS = {'Mercedes-AMG': ['Mercedes-AMG', 'MERCEDES BENZ'], 'MERCEDES BENZ': ['MERCEDES BENZ', 'Mercedes-AMG']}
# Plausible ranges; values outside are dropped as scrape errors.
RANGE = {'hp': (15, 2100), 'torque': (40, 2000), 'accel': (1.8, 40), 'topSpeed': (90, 500), 'weight': (500, 4000)}
# Manual corrections for known errors in the source data.
OVERRIDES = {
    'Mercedes-Benz S 500 (W222)': {'hp': 455, 'torque': 700, 'accel': 4.8},
    'BMW M5 CS': {'weight': 1825},
    'Hummer H1': {'topSpeed': None},
    'Volkswagen Beetle 1.6': {'years': None},
}

def pick(brand, mre, year, ere):
    brands = [b.upper() for b in ALIAS.get(brand, [brand])]
    c = [r for r in d if r['brand'].upper() in brands and re.search(mre, r['model'], re.I)]
    if ere: c = [r for r in c if re.search(ere, r['engine'])]
    if not c: return None
    return min(c, key=lambda r: (abs((r['yearFrom'] or 1900) - year), -sum(1 for f in F if r[f]), -(r['hp'] or 0)))

cars, missing, warn = [], [], []
for i, (name, brand, mre, year, ere) in enumerate(CARS):
    r = pick(brand, mre, year, ere)
    if not r: missing.append(name); continue
    v = {f: r[f] for f in F}
    # Engine name carries the combined system output ("(1063 HP)"); the spec
    # table often lists only the combustion engine for hybrids, or nothing for EVs.
    m = re.search(r'\(([\d,]+)\s*HP\)', r['engine'], re.I)
    if m:
        nhp = float(m.group(1).replace(',', ''))
        if v['hp'] is None or abs(nhp - v['hp']) / nhp > 0.08: v['hp'] = nhp
    v.update(OVERRIDES.get(name, {}))
    for f, (lo, hi) in RANGE.items():
        if v[f] is not None and not lo <= v[f] <= hi:
            warn.append(f'{name}: {f}={v[f]} out of range'); v[f] = None
    # Physics sanity: 0-100 should roughly track power-to-weight.
    if v['accel'] and v['hp'] and v['weight']:
        est = 0.95 * (v['weight'] / v['hp']) ** 0.75 + 0.9
        if v['accel'] / est < 0.5: warn.append(f'{name}: 0-100={v["accel"]} vs est {est:.1f}')
    rnd = lambda x, n=0: None if x is None else (round(x, n) if n else int(round(x)))
    cars.append({
        'id': i + 1, 'name': name,
        'years': v['years'] if 'years' in v else (f"{r['yearFrom']}" + (f"-{r['yearTo']}" if r['yearTo'] and r['yearTo'] != r['yearFrom'] else '') if r['yearFrom'] else None),
        'engine': re.sub(r'\s+', ' ', r['engine']).strip(),
        'fuel': r['fuel'],
        'hp': rnd(v['hp']), 'torque': rnd(v['torque']), 'accel': rnd(v['accel'], 1),
        'topSpeed': rnd(v['topSpeed']), 'weight': rnd(v['weight']),
    })
# cars.js (global) so index.html also works when opened straight from disk.
out = os.path.join(HERE, '..', 'data'); os.makedirs(out, exist_ok=True)
js = json.dumps(cars, ensure_ascii=False, separators=(',', ':'))
open(os.path.join(out, 'cars.js'), 'w', encoding='utf-8').write('// Generated by scripts/build.py. Do not edit.\nwindow.CARS = ' + js + ';\n')
json.dump(cars, open(os.path.join(out, 'cars.json'), 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
print('cars', len(cars), '| missing', missing)
for f in F: print(f, sum(1 for c in cars if c[f] is not None))
print('\n'.join(warn))
